apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mysql-pv
  labels:
    pv: drupal-mysql-pv
spec:
  volumeMode: Filesystem
  storageClassName: "no-provisioner" # Indicates that no provisioner will be used
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: "/drupal-mysql-data"
    type: "Directory" # This is mandatory on Kubernetes v1.11
