apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
  labels:
    pv: drupal-pv
spec:
  capacity:
    storage: "5G"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: "/drupal-data"
  storageClassName: local-storage
