apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mysql-pvc
spec:
  selector:
    matchLabels:
      pv: drupal-mysql-pv
  resources:
    requests:
      storage: "5Gi"
  accessModes:
    - "ReadWriteOnce"
  volumeMode: Filesystem