apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-mysql-pvc
spec:
  volumeMode: Filesystem
  volumeName: drupal-mysql-pv # For direct binding use this instead of selector
  storageClassName: no-provisioner
  resources:
    requests:
      storage: "5Gi"
  accessModes:
    - "ReadWriteOnce"
