apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
  labels:
    pv: drupal-pv
spec:
  volumeMode: Filesystem
  storageClassName: "no-provisioner"
  capacity:
    storage: "5Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: "/drupal-data"
    type: "Directory"
