apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis01
  labels:
    tier: storage
    app: redis
spec:
  capacity:
    storage: "1Gi"
  accessModes:
    - "ReadWriteOnce"
  hostPath:
    path: /redis01