apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
spec:
  serviceName: redis-cluster-service
  replicas: 6
  selector:
    matchLabels:
      app: redis
      tier: app
  template:
    metadata:
      name: redis
      labels:
        app: redis
        tier: app
    spec:
      containers:
        - name: redis
          image: redis:5.0.1-alpine
          command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
          ports:
            - name: client
              containerPort: 6379
            - name: gossip
              containerPort: 16379
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
                  apiVersion: v1
          volumeMounts:
            - name: conf
              mountPath: /conf
              readOnly: false
            - name: data
              mountPath: /data
              readOnly: false
      volumes:
        - name: conf
          configMap:
            name: redis-cluster-configmap
            defaultMode: 0755
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        selector:
          matchLabels:
            tier: storage
            app: redis
        resources:
          requests:
            storage: "1Gi"
        accessModes:
          - "ReadWriteOnce"