# This CAN'T be done via Deployments, unless the number of replicas is 1, insted use StatefulSets.
# A deployment dont care about the PODs uniqueness so it's not possible to manage
# multiple PODs using the same volume.
# So to create multiple stable PVs USE STATEFULSETS