apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: drogo
spec:
  groups:
    - system:authenticated # Group to add on the certificate
  usages:
    - digital signature
    - key encipherment
    - server auth
  request: 