apiVersion: v1
kind: Endpoints
metadata:
  name: external-service #Must be the same name as the service to bind to
subsets:
  - addresses:
      - ip: 172.17.0.9 # IP of a Pod froma nother NS. It simulates an external IP
    ports:
      - port: 80 # Port to forward on Container