apiVersion: v1
kind: Service
metadata: 
  name: service-node-port
spec:
  selector:
    app: service-example
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 80
      nodePort: 30888 # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)