apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: cluster-admin
rules:
  - apiGroups: [""] # List of API groups to apply the role.
    resources: ["nodes"] # List of resources to allow access
    verbs: ["list", "get", "create", "delete"] # List of operations for resources