apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helder-developer
subjects:
  - kind: User
    name: helder
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer