# OBS: On Minikube you MUST enable the ingress addon
# > minikube addons enable ingress

# On any other cluster (AWS,GCP,Azure,OnPremisse) you must install the nginx ingress controller to run this example.
# You cloud also use cloud build in services for http load balancing (https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/)

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / # Tells that this Ingress uses the nginx Ingress Controller
spec:
  rules:
  - http:
      paths:
      - path: /testpath # The URL path to forward http traffic
        pathType: Prefix
        backend:
          serviceName: internal-service # The service name to forward to
          servicePort: 8080   # The port on service to forward