apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: eample-ds
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    # It's possible to use NodeAffnity to select the ScheduleDaemonSetPod Controller that is most stable than the defeult Controller 
    # nodeAffinity:
    # requiredDuringSchedulingIgnoredDuringExecution:
    #   nodeSelectorTerms:
    #   - matchFields:
    #     - key: metadata.name
    #       operator: In
    #       values:
    #       - target-host-name
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      nodeSelector: # This enables the DaemonSet to select which nodes to deploy
        kubernetes.io/os: linux # This will deploy the pods onl on nodes that match the SO as a linux
      # tolerations:
      # # this toleration is to have the daemonset runnable on master nodes
      # # remove it if your masters can't run pods
      # - key: node-role.kubernetes.io/master
      #   effect: NoSchedule
      containers:
      - name: fluentd-elasticsearch
        image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath: # Creates this folder in each node running this pod
          path: /var/log 
      - name: varlibdockercontainers
        hostPath: # Creates this folder in each node running this pod
          path: /var/lib/docker/containers