apiVersion: v1
kind: Pod
metadata: 
  name: example-configmap-env
spec:
  containers:
  - name: base
    image: nginx
    env:
    - name: APP_HOSTNAME
      valueFrom:
        configMapKeyRef: 
          name: example-config-map-yaml #Must be the name of the created config map
          key: hostname
    - name: JSON_CONFIG
      valueFrom:
        configMapKeyRef:
          name: example-config-map-json
          key: conf.json
