apiVersion: v1
kind: Pod
metadata:
  name: example-configmap-file
spec:
  containers:
  - name: base
    image: nginx
    volumeMounts:
    - name: json-configmap # Must be the same defined in volumes
      mountPath: /tmp/json
    - name: yaml-configmap
      mountPath: /tmp/yaml
  volumes:
  - name: json-configmap
    configMap:
      name: example-config-map-json # Must be the name of the created configMap
  - name: yaml-configmap
    configMap:
      name: example-config-map-yaml
