apiVersion: v1
kind: Pod
metadata:
  name: example-configmap-file
spec:
  containers:
  - name: base
    image: nginx
    volumeMounts:
    - name: json-configmap # Must be the same defined in volumes
      mountPath: /tmp/json/conf.json # Use this to mount a single file inside a directory
      subPath: conf.json             # You must specify the file name in mountPath and subPath
    - name: yaml-configmap
      mountPath: /tmp/yaml
    resources:
      limits:
        cpu: "0.1"
        memory: "100m"
  volumes:
  - name: json-configmap
    configMap:
      name: example-config-map-json # Must be the name of the created configMap
  - name: yaml-configmap
    configMap:
      name: example-config-map-yaml
