apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  namespace: mem-example
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      limits: # This is the max resources used by a container(s)
        memory: "200Mi" 
      requests: # This is the start state of the container(s)
        memory: "100Mi" 
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"] # Those arguments are for the stress command

# The args section in the configuration file provides arguments for the Container when it
# starts. The "--vm-bytes", "150M" arguments tell the Container to attempt to allocate
# 150 MiB of memory.