apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: cpu-example
spec:
  containers:
    - name: cpu-demo-ctr
      image: vish/stress
      resources:
        limits:
          cpu: "1"
        requests:
          cpu: "0.5"
      args:
      - -cpus
      - "2"
      - "2"
  nodeSelector: # Will schedule the Pod only on Nodes with the label size=Large
    size: Large