apiVersion: v1
kind: Pod
metadata: 
  name: example-secret-file
spec:
  containers:
  - name: base
    image: nginx
    volumeMounts:
    - name: my-secret #must be the same defined on volumes
      readOnly: true
      mountPath: /tmp
  volumes:
  - name: my-secret
    secret:
      secretName: example-secret # Must be the same name as the created secret
      items:
        - key: literalUsername
          path: username.txt
        - key: base64Username
          path: usernameb64.txt
        