apiVersion: v1
kind: Pod
metadata: 
  name: example-secret-env
spec:
  containers:
  - name: base
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: example-secret # Must be the name of the created secret
          key: literalUsername # Must be one of the keys inside the secret
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: example-secret
          key: base64Password