apiVersion: v1
kind: Pod
metadata:
  name: service-example-pod
  labels:
    app: service-example
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "100m"
          memory: "150Mi"
