apiVersion: v1
kind: Pod
metadata:
  namespace: externalns # Just set another namespace to make it "external" for default ns
  name: service-example-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "100m"
          memory: "150Mi"
