apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs # Name used to create volumes as storageClassName
provisioner: kubernetes.io/aws-ebs # Provisioner for AWS EBS block
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate